sudo: required

dist: trusty

addons:
  chrome: stable

language: node_js

node_js:
  - '8'
  - '10'

env:
  global:
    - DEBUG=nightwatch-api

cache:
  directories:
    - packages/nightwatch-api/node_modules
    - packages/node-example/node_modules
    - packages/jest-example/node_modules
    - packages/cucumber-example/node_modules

branches:
  only:
    - master

notifications:
  email: false

install:
  - cd packages/nightwatch-api
  - npm i
  - npm run pack-into-examples

before_script:
  - jdk_switcher use oraclejdk8
  - java -version
  - google-chrome --product-version

script:
  - npm run lint
  - npm run type-check
  - npm run test:ci
  - npm run check-webdriver-stopped
  - cd ..
  - cd node-example && cd ../nightwatch-api && npm run check-webdriver-stopped && cd ..
  - cd jest-example && cd ../nightwatch-api && npm run check-webdriver-stopped && cd ..
  - cd cucumber-example && cd ../nightwatch-api && npm run check-webdriver-stopped && cd ..

after_success:
  - cd nightwatch-api
  - npm run test:coveralls
  - cd ..

before_deploy:
  - cd website
  - npm i

deploy:
  provider: script
  script: npm run deploy -- --auth $NETLIFY_ACCESS_TOKEN
  skip_cleanup: true
  on:
    branch: master
    node: '10'
