version: '3'
services:
  selenium-hub:
    image: selenium/hub
    logging:
      driver: 'none'
    networks:
      - grid

  node-chrome:
    image: selenium/node-chrome
    logging:
      driver: 'none'
    networks:
      - grid
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  node-firefox:
    image: selenium/node-firefox
    logging:
      driver: 'none'
    networks:
      - grid
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  test-machine:
    build:
      context: .
    networks:
      - grid
    depends_on:
      - selenium-hub
      - node-chrome
      - node-firefox

networks:
  grid:
