version: '3'
services:
  selenium-hub:
    image: selenium/hub
    logging:
      driver: 'none'
    networks:
      - hub

  node-chrome:
    image: selenium/node-chrome
    logging:
      driver: 'none'
    networks:
      - hub
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub

  node-firefox:
    image: selenium/node-firefox
    logging:
      driver: 'none'
    networks:
      - hub
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub

  test-machine:
    build:
      context: .
    networks:
      - hub
    depends_on:
      - selenium-hub
      - node-chrome
      - node-firefox

networks:
  hub:
