version: '2.1'
services:
  selenium-hub:
    image: selenium/hub
    logging:
      driver: 'none'
    networks:
      - grid
    healthcheck:
      test: ['CMD', '/opt/bin/check-grid.sh', '--host', '0.0.0.0', '--port', '4444']
      interval: 15s
      timeout: 30s
      retries: 5

  node-chrome:
    image: selenium/node-chrome
    logging:
      driver: 'none'
    networks:
      - grid
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  node-firefox:
    image: selenium/node-firefox
    logging:
      driver: 'none'
    networks:
      - grid
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  test-machine:
    build:
      context: .
    networks:
      - grid
    depends_on:
      selenium-hub:
        condition: service_healthy

networks:
  grid:
